<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoutineManagementSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('routine_completion_types')->upsert([
            [
                'id' => 1,
                'code' => 'done',
                'display_name' => '実施',
                'description' => '実施したら達成とする',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['id']);

        DB::table('routine_contents')->upsert([
            [
                'id' => 1,
                'category_code' => 'memory',
                'category_name' => '記憶系',
                'name' => '数字瞬間記憶 初級',
                'description' => '数字を短時間で覚える記憶力トレーニングです。',
                'icon_type' => 'emoji',
                'icon_url' => null,
                'theme_color' => '#60a5fa',
                'learning_url' => null,
                'material_url' => null,
                'video_url' => null,
                'default_completion_type_id' => null,
                'default_target_value' => 1,
                'default_estimated_minutes' => 5,
                'sort_order' => 1,
                'is_active' => true,
                'content_code' => 'RC-MEM-001',
                'learning_page_status' => 'draft',
                'difficulty' => 1,
                'estimated_days' => 7,
                'daily_learning_minutes' => 5,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'category_code' => 'focus',
                'category_name' => '集中系',
                'name' => 'ストループ 初級',
                'description' => '色と言葉の違いを見分ける集中力トレーニングです。',
                'icon_type' => 'emoji',
                'icon_url' => null,
                'theme_color' => '#34d399',
                'learning_url' => null,
                'material_url' => null,
                'video_url' => null,
                'default_completion_type_id' => null,
                'default_target_value' => 1,
                'default_estimated_minutes' => 5,
                'sort_order' => 2,
                'is_active' => true,
                'content_code' => 'RC-FOCUS-001',
                'learning_page_status' => 'published',
                'difficulty' => 1,
                'estimated_days' => 10,
                'daily_learning_minutes' => 5,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'category_code' => 'logic',
                'category_name' => '思考系',
                'name' => '数列推理 初級',
                'description' => '数字の並びから法則を見つける論理思考トレーニングです。',
                'icon_type' => 'emoji',
                'icon_url' => null,
                'theme_color' => '#fbbf24',
                'learning_url' => null,
                'material_url' => null,
                'video_url' => null,
                'default_completion_type_id' => null,
                'default_target_value' => 1,
                'default_estimated_minutes' => 10,
                'sort_order' => 3,
                'is_active' => true,
                'content_code' => 'RC-LOGIC-001',
                'learning_page_status' => 'draft',
                'difficulty' => 2,
                'estimated_days' => 14,
                'daily_learning_minutes' => 10,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['id']);

        DB::table('routine_packages')->upsert([
            [
                'id' => 1,
                'package_code' => 'RP-BASIC-001',
                'name' => '記憶力ベーシック',
                'description' => '記憶力を楽しく育てる基本ルーティンです。',
                'icon_type' => 'emoji',
                'icon_url' => null,
                'theme_color' => '#60a5fa',
                'category' => '記憶系',
                'target_grade' => '年中〜小2',
                'target_level' => '初級',
                'tag' => '記憶力',
                'search_tags' => '記憶力,短期記憶,初級',
                'sort_order' => 1,
                'is_active' => true,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'package_code' => 'RP-THINK-001',
                'name' => '考える力ベーシック',
                'description' => '集中力と思考力を育てる基本ルーティンです。',
                'icon_type' => 'emoji',
                'icon_url' => null,
                'theme_color' => '#34d399',
                'category' => '思考系',
                'target_grade' => '小1〜小3',
                'target_level' => '初級〜中級',
                'tag' => '思考力',
                'search_tags' => '論理,判断,集中',
                'sort_order' => 2,
                'is_active' => true,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['id']);

        DB::table('routine_package_items')->upsert([
            [
                'id' => 1,
                'routine_package_id' => 1,
                'routine_content_id' => 1,
                'item_name' => '数字瞬間記憶 初級',
                'target_grade' => '年中〜小2',
                'target_level' => '初級',
                'tag' => '記憶力',
                'completion_type_id' => 1,
                'target_value' => 1,
                'estimated_minutes' => 5,
                'order_no' => 1,
                'is_required' => true,
                'memo' => null,
                'required_days' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'routine_package_id' => 1,
                'routine_content_id' => 2,
                'item_name' => 'ストループ 初級',
                'target_grade' => '年中〜小2',
                'target_level' => '初級',
                'tag' => '集中力',
                'completion_type_id' => 1,
                'target_value' => 1,
                'estimated_minutes' => 5,
                'order_no' => 2,
                'is_required' => true,
                'memo' => null,
                'required_days' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'routine_package_id' => 2,
                'routine_content_id' => 2,
                'item_name' => 'ストループ 初級',
                'target_grade' => '小1〜小3',
                'target_level' => '初級',
                'tag' => '集中力',
                'completion_type_id' => 1,
                'target_value' => 1,
                'estimated_minutes' => 5,
                'order_no' => 1,
                'is_required' => true,
                'memo' => null,
                'required_days' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'routine_package_id' => 2,
                'routine_content_id' => 3,
                'item_name' => '数列推理 初級',
                'target_grade' => '小1〜小3',
                'target_level' => '中級',
                'tag' => '論理思考',
                'completion_type_id' => 1,
                'target_value' => 1,
                'estimated_minutes' => 10,
                'order_no' => 2,
                'is_required' => true,
                'memo' => null,
                'required_days' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['id']);

        DB::table('learning_pages')->upsert([
            [
                'id' => 1,
                'routine_content_id' => 1,
                'page_type' => 'web',
                'title' => '数字瞬間記憶 初級 学習ページ',
                'description' => '数字を短時間で覚えるトレーニングです。',
                'learning_url' => null,
                'status' => 'draft',
                'thumbnail_url' => null,
                'time_limit_seconds' => 30,
                'question_count' => 10,
                'passing_score' => 80,
                'allow_retry' => true,
                'is_shuffle' => false,
                'show_answer' => true,
                'estimated_seconds' => 300,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'routine_content_id' => 2,
                'page_type' => 'web',
                'title' => 'ストループ 初級 学習ページ',
                'description' => '色と言葉の違いを見分けるトレーニングです。',
                'learning_url' => null,
                'status' => 'published',
                'thumbnail_url' => null,
                'time_limit_seconds' => 45,
                'question_count' => 10,
                'passing_score' => 80,
                'allow_retry' => true,
                'is_shuffle' => true,
                'show_answer' => true,
                'estimated_seconds' => 300,
                'created_by' => null,
                'updated_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['id']);
    }
}