<?php

namespace Database\Seeders\A;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('permissions')->insert([
            [
                'id' => 1,
                'name' => 'users.view',
                'display_name' => 'ユーザー管理閲覧',
                'module' => 'ユーザー管理',
                'action' => 'view',
                'description' => 'ユーザー管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'users.create',
                'display_name' => 'ユーザー管理作成',
                'module' => 'ユーザー管理',
                'action' => 'create',
                'description' => 'ユーザー管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'users.update',
                'display_name' => 'ユーザー管理更新',
                'module' => 'ユーザー管理',
                'action' => 'update',
                'description' => 'ユーザー管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'users.delete',
                'display_name' => 'ユーザー管理削除',
                'module' => 'ユーザー管理',
                'action' => 'delete',
                'description' => 'ユーザー管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'students.view',
                'display_name' => '生徒管理閲覧',
                'module' => '生徒管理',
                'action' => 'view',
                'description' => '生徒管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'students.create',
                'display_name' => '生徒管理作成',
                'module' => '生徒管理',
                'action' => 'create',
                'description' => '生徒管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'students.update',
                'display_name' => '生徒管理更新',
                'module' => '生徒管理',
                'action' => 'update',
                'description' => '生徒管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'students.delete',
                'display_name' => '生徒管理削除',
                'module' => '生徒管理',
                'action' => 'delete',
                'description' => '生徒管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'teachers.view',
                'display_name' => '講師管理閲覧',
                'module' => '講師管理',
                'action' => 'view',
                'description' => '講師管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'teachers.create',
                'display_name' => '講師管理作成',
                'module' => '講師管理',
                'action' => 'create',
                'description' => '講師管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'teachers.update',
                'display_name' => '講師管理更新',
                'module' => '講師管理',
                'action' => 'update',
                'description' => '講師管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'teachers.delete',
                'display_name' => '講師管理削除',
                'module' => '講師管理',
                'action' => 'delete',
                'description' => '講師管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'schools.view',
                'display_name' => '教室管理閲覧',
                'module' => '教室管理',
                'action' => 'view',
                'description' => '教室管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'schools.create',
                'display_name' => '教室管理作成',
                'module' => '教室管理',
                'action' => 'create',
                'description' => '教室管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'schools.update',
                'display_name' => '教室管理更新',
                'module' => '教室管理',
                'action' => 'update',
                'description' => '教室管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'schools.delete',
                'display_name' => '教室管理削除',
                'module' => '教室管理',
                'action' => 'delete',
                'description' => '教室管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'courses.view',
                'display_name' => 'コース管理閲覧',
                'module' => 'コース管理',
                'action' => 'view',
                'description' => 'コース管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'courses.create',
                'display_name' => 'コース管理作成',
                'module' => 'コース管理',
                'action' => 'create',
                'description' => 'コース管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'courses.update',
                'display_name' => 'コース管理更新',
                'module' => 'コース管理',
                'action' => 'update',
                'description' => 'コース管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'courses.delete',
                'display_name' => 'コース管理削除',
                'module' => 'コース管理',
                'action' => 'delete',
                'description' => 'コース管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'lessons.view',
                'display_name' => '授業管理閲覧',
                'module' => '授業管理',
                'action' => 'view',
                'description' => '授業管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'lessons.create',
                'display_name' => '授業管理作成',
                'module' => '授業管理',
                'action' => 'create',
                'description' => '授業管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'lessons.update',
                'display_name' => '授業管理更新',
                'module' => '授業管理',
                'action' => 'update',
                'description' => '授業管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'lessons.delete',
                'display_name' => '授業管理削除',
                'module' => '授業管理',
                'action' => 'delete',
                'description' => '授業管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'attendances.view',
                'display_name' => '出欠管理閲覧',
                'module' => '出欠管理',
                'action' => 'view',
                'description' => '出欠管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'attendances.create',
                'display_name' => '出欠管理作成',
                'module' => '出欠管理',
                'action' => 'create',
                'description' => '出欠管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'attendances.update',
                'display_name' => '出欠管理更新',
                'module' => '出欠管理',
                'action' => 'update',
                'description' => '出欠管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'attendances.delete',
                'display_name' => '出欠管理削除',
                'module' => '出欠管理',
                'action' => 'delete',
                'description' => '出欠管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'learning_plans.view',
                'display_name' => '進捗管理閲覧',
                'module' => '進捗管理',
                'action' => 'view',
                'description' => '進捗管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'learning_plans.create',
                'display_name' => '進捗管理作成',
                'module' => '進捗管理',
                'action' => 'create',
                'description' => '進捗管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name' => 'learning_plans.update',
                'display_name' => '進捗管理更新',
                'module' => '進捗管理',
                'action' => 'update',
                'description' => '進捗管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name' => 'learning_plans.delete',
                'display_name' => '進捗管理削除',
                'module' => '進捗管理',
                'action' => 'delete',
                'description' => '進捗管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => 'routines.view',
                'display_name' => 'ルーティン管理閲覧',
                'module' => 'ルーティン管理',
                'action' => 'view',
                'description' => 'ルーティン管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => 'routines.create',
                'display_name' => 'ルーティン管理作成',
                'module' => 'ルーティン管理',
                'action' => 'create',
                'description' => 'ルーティン管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => 'routines.update',
                'display_name' => 'ルーティン管理更新',
                'module' => 'ルーティン管理',
                'action' => 'update',
                'description' => 'ルーティン管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name' => 'routines.delete',
                'display_name' => 'ルーティン管理削除',
                'module' => 'ルーティン管理',
                'action' => 'delete',
                'description' => 'ルーティン管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'name' => 'invoices.view',
                'display_name' => '請求管理閲覧',
                'module' => '請求管理',
                'action' => 'view',
                'description' => '請求管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name' => 'invoices.create',
                'display_name' => '請求管理作成',
                'module' => '請求管理',
                'action' => 'create',
                'description' => '請求管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'name' => 'invoices.update',
                'display_name' => '請求管理更新',
                'module' => '請求管理',
                'action' => 'update',
                'description' => '請求管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'name' => 'invoices.delete',
                'display_name' => '請求管理削除',
                'module' => '請求管理',
                'action' => 'delete',
                'description' => '請求管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'name' => 'notifications.view',
                'display_name' => '通知管理閲覧',
                'module' => '通知管理',
                'action' => 'view',
                'description' => '通知管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'name' => 'notifications.create',
                'display_name' => '通知管理作成',
                'module' => '通知管理',
                'action' => 'create',
                'description' => '通知管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'name' => 'notifications.update',
                'display_name' => '通知管理更新',
                'module' => '通知管理',
                'action' => 'update',
                'description' => '通知管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'name' => 'notifications.delete',
                'display_name' => '通知管理削除',
                'module' => '通知管理',
                'action' => 'delete',
                'description' => '通知管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'name' => 'contacts.view',
                'display_name' => '問い合わせ管理閲覧',
                'module' => '問い合わせ管理',
                'action' => 'view',
                'description' => '問い合わせ管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'name' => 'contacts.create',
                'display_name' => '問い合わせ管理作成',
                'module' => '問い合わせ管理',
                'action' => 'create',
                'description' => '問い合わせ管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'name' => 'contacts.update',
                'display_name' => '問い合わせ管理更新',
                'module' => '問い合わせ管理',
                'action' => 'update',
                'description' => '問い合わせ管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'name' => 'contacts.delete',
                'display_name' => '問い合わせ管理削除',
                'module' => '問い合わせ管理',
                'action' => 'delete',
                'description' => '問い合わせ管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'name' => 'points.view',
                'display_name' => 'ポイント管理閲覧',
                'module' => 'ポイント管理',
                'action' => 'view',
                'description' => 'ポイント管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'name' => 'points.create',
                'display_name' => 'ポイント管理作成',
                'module' => 'ポイント管理',
                'action' => 'create',
                'description' => 'ポイント管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'name' => 'points.update',
                'display_name' => 'ポイント管理更新',
                'module' => 'ポイント管理',
                'action' => 'update',
                'description' => 'ポイント管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'name' => 'points.delete',
                'display_name' => 'ポイント管理削除',
                'module' => 'ポイント管理',
                'action' => 'delete',
                'description' => 'ポイント管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'name' => 'badges.view',
                'display_name' => 'バッジ管理閲覧',
                'module' => 'バッジ管理',
                'action' => 'view',
                'description' => 'バッジ管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'name' => 'badges.create',
                'display_name' => 'バッジ管理作成',
                'module' => 'バッジ管理',
                'action' => 'create',
                'description' => 'バッジ管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'name' => 'badges.update',
                'display_name' => 'バッジ管理更新',
                'module' => 'バッジ管理',
                'action' => 'update',
                'description' => 'バッジ管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'name' => 'badges.delete',
                'display_name' => 'バッジ管理削除',
                'module' => 'バッジ管理',
                'action' => 'delete',
                'description' => 'バッジ管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'name' => 'events.view',
                'display_name' => 'イベント管理閲覧',
                'module' => 'イベント管理',
                'action' => 'view',
                'description' => 'イベント管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'name' => 'events.create',
                'display_name' => 'イベント管理作成',
                'module' => 'イベント管理',
                'action' => 'create',
                'description' => 'イベント管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'name' => 'events.update',
                'display_name' => 'イベント管理更新',
                'module' => 'イベント管理',
                'action' => 'update',
                'description' => 'イベント管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'name' => 'events.delete',
                'display_name' => 'イベント管理削除',
                'module' => 'イベント管理',
                'action' => 'delete',
                'description' => 'イベント管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'name' => 'shop.view',
                'display_name' => 'ショップ管理閲覧',
                'module' => 'ショップ管理',
                'action' => 'view',
                'description' => 'ショップ管理の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'name' => 'shop.create',
                'display_name' => 'ショップ管理作成',
                'module' => 'ショップ管理',
                'action' => 'create',
                'description' => 'ショップ管理の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'name' => 'shop.update',
                'display_name' => 'ショップ管理更新',
                'module' => 'ショップ管理',
                'action' => 'update',
                'description' => 'ショップ管理の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'name' => 'shop.delete',
                'display_name' => 'ショップ管理削除',
                'module' => 'ショップ管理',
                'action' => 'delete',
                'description' => 'ショップ管理の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'name' => 'settings.view',
                'display_name' => 'システム設定閲覧',
                'module' => 'システム設定',
                'action' => 'view',
                'description' => 'システム設定の閲覧を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'name' => 'settings.create',
                'display_name' => 'システム設定作成',
                'module' => 'システム設定',
                'action' => 'create',
                'description' => 'システム設定の作成を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'name' => 'settings.update',
                'display_name' => 'システム設定更新',
                'module' => 'システム設定',
                'action' => 'update',
                'description' => 'システム設定の更新を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'name' => 'settings.delete',
                'display_name' => 'システム設定削除',
                'module' => 'システム設定',
                'action' => 'delete',
                'description' => 'システム設定の削除を許可します。',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
