FROM node:22 AS assets

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:latest

WORKDIR /var/www/html

COPY . /var/www/html
COPY --from=assets /app/public/build /var/www/html/public/build
COPY docker/nginx/ecs.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
