FROM 166818437537.dkr.ecr.ap-northeast-1.amazonaws.com/lifeforce-system:latest AS app

FROM nginx:latest

WORKDIR /var/www/html

COPY . /var/www/html
COPY --from=app /var/www/html/public/build /var/www/html/public/build
COPY docker/nginx/ecs.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
