@extends('layouts.admin')
@section('title','商品交換所｜交換履歴')
@section('content')
<link rel="stylesheet" href="{{ asset('css/admin/wakuwaku/reward-exchange.css') }}">
<div class="rex-page"><header class="rex-header"><div><p>わくわく ＞ 商品交換所 ＞ 交換履歴</p><h1>交換履歴</h1><span>受渡完了・却下・取消になった申請を、生徒別・商品別に確認します。未完了の申請は申請情報で管理します。</span></div><div class="rex-header-links"><a href="{{ route('admin.wakuwaku.reward-exchange.products') }}">商品一覧</a><a href="{{ route('admin.wakuwaku.reward-exchange.applications') }}">申請情報</a></div></header>
@include('admin.wakuwaku.reward-exchange.flash')
<section class="rex-summary rex-summary-wide">@foreach(['total'=>'総申請','approved'=>'承認','delivered'=>'受渡完了','rejected'=>'却下','cancelled'=>'取消','used'=>'使用Pt','returned'=>'返還Pt','cost'=>'商品原価'] as $k=>$l)<article class="summary-{{ $k }}"><strong>{{ number_format($summary[$k]) }}@if(in_array($k,['used','returned']))<small>pt</small>@elseif($k==='cost')<small>円</small>@endif</strong><span>{{ $l }}</span></article>@endforeach</section>
@include('admin.wakuwaku.reward-exchange.request-filter',['historyMode'=>true])
<section class="rex-table-card"><table><thead><tr><th>履歴／申請</th><th>生徒／教室</th><th>商品／カテゴリ</th><th>数量</th><th>使用／返還Pt</th><th>原価</th><th>状態／受渡</th><th>担当／完了</th><th>連携ID</th><th>操作</th></tr></thead><tbody>
@forelse($rows as $row)
@php $image=$row->item?->mainImage?asset('storage/'.$row->item->mainImage->image_path):null; @endphp
<tr><td><b>#{{ $row->id }}</b><small>{{ $row->request_number }}<br>{{ optional($row->requested_at)->format('Y/m/d H:i') }}</small></td><td><b>{{ $row->student?->last_name }} {{ $row->student?->first_name }}</b><small>{{ $row->student?->school?->name ?? '教室未設定' }}</small></td><td><div class="rex-table-product">@if($image)<img src="{{ $image }}" alt="">@else<span>🎁</span>@endif<div><b>{{ $row->item?->name ?? '削除済み商品' }}</b><small><i class="rex-category-badge">{{ $row->item?->category?->name ?? '未分類' }}</i></small></div></div></td><td>{{ $row->quantity }}</td><td><b>{{ number_format($row->request_points) }} pt</b>@if($row->returned_points>0)<small class="rex-returned">返還 {{ number_format($row->returned_points) }} pt</small>@else<small>返還なし</small>@endif</td><td>{{ number_format(($row->item?->cost_price ?? 0)*$row->quantity) }}円</td><td><span class="rex-status s-{{ $row->status }}">{{ $row->status_name }}</span><small>{{ $row->delivery_method==='shipping'?'🚚 発送':'🏫 教室受渡' }}</small>@if(in_array($row->status,['rejected','cancelled']))<div class="rex-restoration-badges"><span>ポイント返還済</span><span>在庫戻し済</span></div>@endif</td><td>{{ $row->handler?->name ?? '未担当' }}<small>{{ optional($row->delivered_at ?? $row->rejected_at ?? $row->cancelled_at)->format('Y/m/d H:i') ?? '-' }}</small></td><td>@if($row->point_transaction_id)<a class="rex-link-id" href="{{ route('admin.wakuwaku.points.history',['student_id'=>$row->student_id]) }}">Pt #{{ $row->point_transaction_id }}</a>@else<span class="rex-muted">Pt -</span>@endif<small>@if($row->account_transaction_id)<a class="rex-link-id" href="{{ route('admin.operations.classroom-accounting.transactions.index',['source_id'=>$row->account_transaction_id]) }}">会計 #{{ $row->account_transaction_id }}</a>@else会計 -@endif</small></td><td><button type="button" class="rex-detail" data-url="{{ route('admin.wakuwaku.reward-exchange.show',$row) }}">詳細</button></td></tr>
@empty<tr><td colspan="10" class="rex-empty"><span>📚</span><b>交換履歴がありません</b></td></tr>@endforelse
</tbody></table></section><div class="rex-list-footer"><span>全 {{ number_format($rows->total()) }} 件中 {{ number_format($rows->firstItem() ?? 0) }}〜{{ number_format($rows->lastItem() ?? 0) }} 件を表示</span><div class="rex-pagination">{{ $rows->links() }}</div></div></div>
@include('admin.wakuwaku.reward-exchange.detail-drawer')<script src="{{ asset('js/admin/wakuwaku/reward-exchange.js') }}"></script>
@endsection
